### ISSUE TITLE
Parse error when pattern matching in function-argument

### ISSUE THREAD

**Issue by teppix** [intellij-elm/intellij-elm#742]
Tested in latest release, 4.3.1

The code below is valid elm-code, but `f2` yields a syntax error.
It seems like itellij-elm does not like pattern matches in function without parens

A workaround is to wrap every such argument in parens. This is however not possible if using elm-format, since it automatically removes the parens unless the type constructor in question accepts one or more arguments.

view in [ellie-app](https://ellie-app.com/cFymb5YVGzba1)

```elm
module Main exposing (..)

import Html


type MyType
    = TheOnlyConstructor

-- valid syntax according to intellij-elm
f1 : MyType -> String
f1 (TheOnlyConstructor) =
    "f1 output"


-- invalid syntax according to intellij-elm
f2 : MyType -> String
f2 TheOnlyConstructor =
    "f2 output"


main =
    Html.div []
        [ Html.div [] [ Html.text <| f1 TheOnlyConstructor]
        , Html.div [] [ Html.text <| f2 TheOnlyConstructor]
        ]

```

Error message:

![image](https://user-images.githubusercontent.com/1038040/111765363-8f973e80-88a4-11eb-80f8-ade1de9629d7.png)

**Comment by clojj** [comment]
Hi @teppix 
I think that I have found a fix in the parser.. didn't know Elm had this 'edge case' (I would love to have full function-matching like Haskell for Elm)
@klazuka 
a merge won't work before merging my master branch (haven't created PR yet)
but maybe cherry picking will do... ?
https://github.com/clojj/intellij-elm/commit/1e46aca880a5b0e930c2e98319ee8cfa89b6f39a

**Comment by cies** [comment]
Hi all. I took stewardship over this project. I will certainly merge this fix if it supplied as a PR. :)
