### ISSUE TITLE
Jump to File Member does nothing

### ISSUE THREAD

**Issue by lydell** [intellij-elm/intellij-elm#820]
### What happened?

Hi!

A small regression with the new release :)

The _File Member_ dialog lists file members correctly, but when selecting one of them it does not jump to it.

<img width="575" alt="image" src="https://github.com/intellij-elm/intellij-elm/assets/2142817/861a3893-30c3-4707-9ff7-a86e70290176">

### Relevant log output or stack trace

```shell
Sorry, I don’t know where to find logs
```

### Steps to reproduce

1. Open a valid Elm file
2. Open the command palette
3. Choose ”File Member”
4. A small window opens, listing all definition in the file
5. Choose one and activate it by clicking or pressing Enter

Actual: Nothing happens.
Expected: Jump to that definition. (It used to work in the old version.)

### IntelliJ IDE details (should contain the Elm plugin version and OS details)

JetBrains Rider 2024.1.1
Build #RD-241.14494.325, built on April 16, 2024
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
.NET Core v8.0.1 ARM64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  documentation.show.toolbar=true
  ide.experimental.ui=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  me.laria.code.idea_caseconv (0.7.1)
  io.binx.cfnlint.plugin (0.1.28)
  intellij-elm (5.0.0-beta28)
  name.kropp.intellij.makefile (241.14494.150)
  AceJump (3.8.19)
  IdeaVIM (2.10.2)
  com.intellij.mermaid (0.0.21+IJ.232)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.ml.llm (241.14494.320)
  com.github.copilot (1.5.2.5345)
  io.github.mishkun.ideavimsneak (1.2.0)

**Comment by cies** [comment]
Thanks for the compete report!

**Comment by lydell** [comment]
It works again in 5.0.0.
