### ISSUE TITLE
Failed to attach elm.json to an existing project

### ISSUE THREAD

**Issue by ahankinson** [intellij-elm/intellij-elm#827]
### What happened?

When opening a project that I haven't opened in a while, I get the prompt to attach an elm.json file. I choose the appropriate file, but then an error about not having a valid Lambdera executable set pops up. I don't have that installed, so I cannot set it. 

![image](https://github.com/intellij-elm/intellij-elm/assets/163183/a8e822eb-0fa0-4386-a57d-57ab32887583)

To work around this I set the executable path to /usr/bin/true and it seemed to work after that. 

### Steps to reproduce

I was able to reproduce it on my own system simply by removing the /usr/bin/true from the settings and then selecting Tools -> Elm -> Attach elm.json project file

### IntelliJ IDE details (should contain the Elm plugin version and OS details)

IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 12, 2023
...
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.mac.bigsur.window.with.tabs.enabled=false
    ide.experimental.ui=true

Non-Bundled Plugins:
    monokai-pro (1.10)
    org.jetbrains.plugins.go-template (232.9921.62)
    intellij-elm (5.0.0)
    com.markskelton.one-dark-theme (5.10.0)
    ir.msdehghan.plugins.ansible (0.92)
    org.jetbrains.plugins.go (232.9921.28)
    com.1v0.dev.hugo-intellij-plugin (0.4.10)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    Pythonid (232.9921.47)

Kotlin: 232-1.9.0-IJ9921.47

**Comment by BenjaminDebeerst** [comment]
This is a known issue in 5.0.0, fixed in https://github.com/intellij-elm/intellij-elm/commit/3b06b0a605925e55d8d0f63eb688307963f8e715, which is already part of release 5.0.1-beta1.

**Comment by ahankinson** [comment]
OK, if it's fixed I will close it. Thank you!
